nelmio_cors:
    defaults:
        allow_origin: ['*']  # Allow requests from any origin
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']  # Specify allowed methods
        allow_headers: ['*']  # Allow all headers
        expose_headers: ['Content-Type', 'Authorization']  # Specify which headers to expose
        max_age: 3600  # Cache CORS results for this many seconds
        allow_credentials: true  # Specify whether credentials are allowed
